// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1BRniO5K11PE8fVWuVHElEwsLcqzqcIQ',
    appId: '1:925390015146:web:c0c1aa4b4faadc7fda5ed3',
    messagingSenderId: '925390015146',
    projectId: 'qtask-backend-service-c667a2',
    authDomain: 'qtask-backend-service-c667a2.firebaseapp.com',
    storageBucket: 'qtask-backend-service-c667a2.firebasestorage.app',
    measurementId: 'G-PZXWDTLYY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNMwmRipoQwaDw9MGsVmtSN9odi9c-IWY',
    appId: '1:925390015146:android:98fcac29c18f6e7cda5ed3',
    messagingSenderId: '925390015146',
    projectId: 'qtask-backend-service-c667a2',
    storageBucket: 'qtask-backend-service-c667a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhtuex5u9E-17Ch976oxL1k42mRWwr1s',
    appId: '1:925390015146:ios:baf044711b6579bada5ed3',
    messagingSenderId: '925390015146',
    projectId: 'qtask-backend-service-c667a2',
    storageBucket: 'qtask-backend-service-c667a2.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhtuex5u9E-17Ch976oxL1k42mRWwr1s',
    appId: '1:925390015146:ios:a0c38f98a1cd58f2da5ed3',
    messagingSenderId: '925390015146',
    projectId: 'qtask-backend-service-c667a2',
    storageBucket: 'qtask-backend-service-c667a2.firebasestorage.app',
    iosBundleId: 'com.md5.qTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1BRniO5K11PE8fVWuVHElEwsLcqzqcIQ',
    appId: '1:925390015146:web:00d91022e2082507da5ed3',
    messagingSenderId: '925390015146',
    projectId: 'qtask-backend-service-c667a2',
    authDomain: 'qtask-backend-service-c667a2.firebaseapp.com',
    storageBucket: 'qtask-backend-service-c667a2.firebasestorage.app',
    measurementId: 'G-Z4BRC0CZS3',
  );
}
